#Server Port
server: 
  port: 8890

#Oracle DB Setting
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: yeonoosolution
    password: yeonoosolution
    
  mvc:
    hiddenmethod: 
      filter: 
        enabled: true
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        
#file size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  
  devtools:
    restart:
      enabled: true
      
#Mybatis     
mybatis :
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
  
